import { artistKey, needsAttribution, type Kind, type WorkDraft } from "./types";

/** Documentation, stock, and ephemera, whatever type the source gives the record. */
const NOT_ART =
  /\b(stereo(graph|view|card)s?|cartes? de visite|carte-de-visite|cabinet cards?|lantern slides?|post ?cards?|x-rays?|radiographs?|micrographs?|screen ?shots?|logos?|diagrams?|installation views?|exhibition views?|gallery views?|trade cards?|baseball cards?|cigarette cards?|achterzijde|pages? \d+)\b/i;

/** "A New Map of Virginia", not "Children studying map of city". */
const MAP_TITLE = /^(an? |the )?(\S+ ){0,3}maps? of\b/i;

/** "Albumen print from glass negative" is a photograph; "glass plate negative" is only the plate. */
function isNegative(medium: string): boolean {
  return /\bnegatives?\b/i.test(medium) && !/\b(prints?|from)\b/i.test(medium);
}

const MACHINE_MADE = /\b(ai[- ]generated|generated by ai|midjourney|stable diffusion|dall-?e|text-to-image)\b/i;

/** Kinds whose sources are open uploads or documentary archives, so a named maker is the floor. */
const NAMED: ReadonlySet<Kind> = new Set(["photograph", "collage", "digital"]);

/** Why a draft stays off the walls, or null when it may hang. */
export function rejectReason(work: WorkDraft): string | null {
  const text = `${work.title} ${work.medium}`;
  if (MACHINE_MADE.test(text)) return "machine-made";
  if (NOT_ART.test(text) || MAP_TITLE.test(work.title) || isNegative(work.medium)) return "not art";
  const named = artistKey(work.artist) !== null;
  if (!named && needsAttribution(work.license)) return "unnamed, attribution licence";
  if (!named && NAMED.has(work.kind)) return `unnamed ${work.kind}`;
  return null;
}

/** Words that name the object rather than a picture on it, for sources without a type field. */
export const OBJECT_WORDS =
  /\b(vases?|vessels?|jars?|bowls?|cups?|bottles?|ewers?|teapots?|blocks?|sculptures?|statues?|statuettes?|busts?|figurines?|terracotta|ceramics?|porcelain|stoneware|earthenware|pottery|bronzes?|textiles?|tapestr(y|ies)|carpets?|rugs?|coins?|medals?|jewel(le)?ry|furniture|chairs?|armou?r|swords?|helmets?|masks?|baskets?|costumes?|dress(es)?|garments?|kimonos?|netsuke|inro|boxes|lacquer|beds?|four poster|salvers?|trays?|spoons?|tankards?|candlesticks?|silverware|plaques?)\b/i;

const KIND_WORDS: [RegExp, Kind][] = [
  [/\bposters?\b/i, "poster"],
  [/\b(collages?|photomontages?|papiers? coll[ée]s?)\b/i, "collage"],
  [/\b(photographs?|photography|daguerreotypes?|albumen|gelatin silver|platinum print|salted paper|cyanotypes?)\b/i, "photograph"],
  [/\b(paintings?|painted on|gouaches?|watercolou?rs?|tempera|oil on|oils? painting|pastels?|miniatures?|hanging scroll)\b/i, "painting"],
  [/\b(drawings?|sketch(es)?|chalk|charcoal|pen and ink|graphite)\b/i, "drawing"],
  [
    /\b(prints?|woodcuts?|wood engravings?|engravings?|etchings?|lithographs?|lithography|aquatints?|mezzotints?|drypoints?|intaglio|xylographs?|mokuhanga|ukiyo-e|screenprints?|serigraphs?)\b/i,
    "print",
  ],
];

/** The first kind named in free text, most specific first. */
export function kindFromText(text: string): Kind | null {
  for (const [pattern, kind] of KIND_WORDS) {
    if (pattern.test(text)) return kind;
  }
  return null;
}
